server:
  port: 8080
  servlet:
    context-path: /
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp 

  datasource:
    url: jdbc:mysql://localhost:3306/ynd?serverTimezone=Asia/Seoul
    username: ynd
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    
    
    
    

